
class KnowledgeBase:
    def __init__(self):
        self.facts = []

    def add_fact(self, fact):
        self.facts.append(fact)

    def get_related_people(self, person, relation):
        related_people = []
        for fact in self.facts:
            if person == fact[0] and relation == fact[1]:
                related_people.append(fact[2])
        return related_people

# Create a knowledge base and add some facts
kb = KnowledgeBase()
# A.	Orang Tua
kb.add_fact(("Hadi", "orang tua dari", "Desi"))
kb.add_fact(("Hadi", "orang tua dari", "Wahyu"))
kb.add_fact(("Hadi", "orang tua dari", "Rina"))
kb.add_fact(("Hadi", "orang tua dari", "Ardi"))
kb.add_fact(("Retno", "orang tua dari", "Desi"))
kb.add_fact(("Retno", "orang tua dari", "Wahyu"))
kb.add_fact(("Retno", "orang tua dari", "Rina"))
kb.add_fact(("Retno", "orang tua dari", "Ardi"))
kb.add_fact(("Bayu", "orang tua dari", "Tari"))
kb.add_fact(("Bayu", "orang tua dari", "Nurul"))
kb.add_fact(("Bayu", "orang tua dari", "Yanto"))
kb.add_fact(("Desi", "orang tua dari", "Tari"))
kb.add_fact(("Desi", "orang tua dari", "Nurul"))
kb.add_fact(("Desi", "orang tua dari", "Yanto"))
kb.add_fact(("Rina", "orang tua dari", "Hamzah"))
kb.add_fact(("Ardi", "orang tua dari", "Eka"))
kb.add_fact(("Ardi", "orang tua dari", "Mira"))
kb.add_fact(("Ardi", "orang tua dari", "Bastian"))
kb.add_fact(("Ana", "orang tua dari", "Eka"))
kb.add_fact(("Ana", "orang tua dari", "Mira"))
kb.add_fact(("Ana", "orang tua dari", "Bastian"))
kb.add_fact(("Ridho", "orang tua dari", "wanda"))
kb.add_fact(("Tari", "orang tua dari", "wanda"))
kb.add_fact(("Nurul", "orang tua dari", "Aji"))
kb.add_fact(("Nurul", "orang tua dari", "Gunawan"))
kb.add_fact(("Mira", "orang tua dari", "Anggun"))
kb.add_fact(("Mira", "orang tua dari", "Boy"))
#B.	Saudara Laki2
kb.add_fact(("Wahyu", "saudara laki-laki dari", "Desi"))
kb.add_fact(("Wahyu", "saudara laki-laki dari", "Rina"))
kb.add_fact(("Wahyu", "saudara laki-laki dari", "Ardi"))
kb.add_fact(("Ardi", "saudara laki-laki dari", "Desi"))
kb.add_fact(("Ardi", "saudara laki-laki dari", "Rina"))
kb.add_fact(("Ardi", "saudara laki-laki dari", "Wahyu"))
kb.add_fact(("Yanto", "saudara laki-laki dari", "Tari"))
kb.add_fact(("Yanto", "saudara laki-laki dari", "Nurul"))
kb.add_fact(("Bastian", "saudara laki-laki dari", "Eka"))
kb.add_fact(("Bastian", "saudara laki-laki dari", "Mira"))
kb.add_fact(("Aji", "saudara laki-laki dari", "Gunawan"))
kb.add_fact(("Gunawan", "saudara laki-laki dari", "Aji"))
kb.add_fact(("Boy", "saudara laki-laki dari", "Anggun"))
# saudara perempuan
kb.add_fact(("Desi", "saudara perempuan dari", "Rina"))
kb.add_fact(("Desi", "saudara perempuan dari", "Ardi"))
kb.add_fact(("Rina", "saudara perempuan dari", "Desi"))
kb.add_fact(("Rina", "saudara perempuan dari", "Wahyu"))
kb.add_fact(("Rina", "saudara perempuan dari", "Ardi"))
kb.add_fact(("Tari", "saudara perempuan dari", "Nurul"))
kb.add_fact(("Tari", "saudara perempuan dari", "Yanto"))
kb.add_fact(("Nurul", "saudara perempuan dari", "Tari"))
kb.add_fact(("Nurul", "saudara perempuan dari", "Yanto"))
kb.add_fact(("Eka", "saudara perempuan dari", "Mira"))
kb.add_fact(("Eka", "saudara perempuan dari", "Bastian"))
kb.add_fact(("Mira", "saudara perempuan dari", "Eka"))
kb.add_fact(("Mira", "saudara perempuan dari", "Bastian"))
kb.add_fact(("Anggun", "saudara perempuan dari", "Boy"))
# Paman
kb.add_fact(("Bayu", "paman dari", "Hamzah"))
kb.add_fact(("Bayu", "paman dari", "Eka"))
kb.add_fact(("Bayu", "paman dari", "Mira"))
kb.add_fact(("Bayu", "paman dari", "Bastian"))
kb.add_fact(("Wahyu", "paman dari", "Tari"))
kb.add_fact(("Wahyu", "paman dari", "Nurul"))
kb.add_fact(("Wahyu", "paman dari", "Yanto"))
kb.add_fact(("Wahyu", "paman dari", "Hamzah"))
kb.add_fact(("Wahyu", "paman dari", "Eka"))
kb.add_fact(("Wahyu", "paman dari", "Mira"))
kb.add_fact(("Wahyu", "paman dari", "Bastian"))
kb.add_fact(("Ardi", "paman dari", "Tari"))
kb.add_fact(("Ardi", "paman dari", "Nurul"))
kb.add_fact(("Ardi", "paman dari", "Yanto"))
kb.add_fact(("Ardi", "paman dari", "Hamzah"))
kb.add_fact(("Yanto", "paman dari", "Wanda"))
kb.add_fact(("Yanto", "paman dari", "Aji"))
kb.add_fact(("Yanto", "paman dari", "Gunawan"))
kb.add_fact(("Yanto", "paman dari", "Anggun"))
kb.add_fact(("Yanto", "paman dari", "Boy"))
kb.add_fact(("Hamzah", "paman dari", "Wanda"))
kb.add_fact(("Hamzah", "paman dari", "Aji"))
kb.add_fact(("Hamzah", "paman dari", "Gunawan"))
kb.add_fact(("Hamzah", "paman dari", "Anggun"))
kb.add_fact(("Hamzah", "paman dari", "Boy"))
kb.add_fact(("Bastian", "paman dari", "Wanda"))
kb.add_fact(("Bastian", "paman dari", "Aji"))
kb.add_fact(("Bastian", "paman dari", "Gunawan"))
kb.add_fact(("Bastian", "paman dari", "Anggun"))
kb.add_fact(("Bastian", "paman dari", "Boy"))
kb.add_fact(("Ridho", "paman dari", "Aji"))
kb.add_fact(("Ridho", "paman dari", "Gunawan"))
kb.add_fact(("Ridho", "paman dari", "Anggun"))
kb.add_fact(("Ridho", "paman dari", "Boy"))
# Bibi
kb.add_fact(("Desi", "bibi dari", "Hamzah"))
kb.add_fact(("Desi", "bibi dari", "Eka"))
kb.add_fact(("Desi", "bibi dari", "Mira"))
kb.add_fact(("Desi", "bibi dari", "Bastian"))
kb.add_fact(("Rina", "bibi dari", "Tari"))
kb.add_fact(("Rina", "bibi dari", "Nurul"))
kb.add_fact(("Rina", "bibi dari", "Yanto"))
kb.add_fact(("Rina", "bibi dari", "Eka"))
kb.add_fact(("Rina", "bibi dari", "Mira"))
kb.add_fact(("Rina", "bibi dari", "Bastian"))
kb.add_fact(("Rina", "bibi dari", "Ridho"))
kb.add_fact(("Ana", "bibi dari", "Tari"))
kb.add_fact(("Ana", "bibi dari", "Nurul"))
kb.add_fact(("Ana", "bibi dari", "Yanto"))
kb.add_fact(("Ana", "bibi dari", "Ridho"))
kb.add_fact(("Nurul", "bibi dari", "Wanda"))
kb.add_fact(("Nurul", "bibi dari", "Anggun"))
kb.add_fact(("Nurul", "bibi dari", "Boy"))
kb.add_fact(("Eka", "bibi dari", "Wanda"))
kb.add_fact(("Eka", "bibi dari", "Aji"))
kb.add_fact(("Eka", "bibi dari", "Gunawan"))
kb.add_fact(("Eka", "bibi dari", "Anggun"))
kb.add_fact(("Eka", "bibi dari", "Boy"))
kb.add_fact(("Mira", "bibi dari", "Wanda"))
kb.add_fact(("Mira", "bibi dari", "Aji"))
kb.add_fact(("Mira", "bibi dari", "Gunawan"))
#Kakek
kb.add_fact(("Hadi", "kakek dari", "Tari"))
kb.add_fact(("Hadi", "kakek dari", "Nurul"))
kb.add_fact(("Hadi", "kakek dari", "Yanto"))
kb.add_fact(("Hadi", "kakek dari", "Hamzah"))
kb.add_fact(("Hadi", "kakek dari", "Eka"))
kb.add_fact(("Hadi", "kakek dari", "Mira"))
kb.add_fact(("Hadi", "kakek dari", "Bastian"))
kb.add_fact(("Hadi", "kakek dari", "Ridho"))
kb.add_fact(("Bayu", "kakek dari", "Wanda"))
kb.add_fact(("Bayu", "kakek dari", "Aji"))
kb.add_fact(("Bayu", "kakek dari", "Gunawan"))
kb.add_fact(("Ardi", "kakek dari", "Anggun"))
kb.add_fact(("Ardi", "kakek dari", "Boy"))
# nenek
kb.add_fact(("Retno", "nenek dari", "Tari"))
kb.add_fact(("Retno", "nenek dari", "Nurul"))
kb.add_fact(("Retno", "nenek dari", "Yanto"))
kb.add_fact(("Retno", "nenek dari", "Hamzah"))
kb.add_fact(("Retno", "nenek dari", "Eka"))
kb.add_fact(("Retno", "nenek dari", "Mira"))
kb.add_fact(("Retno", "nenek dari", "Bastian"))
kb.add_fact(("Retno", "nenek dari", "Ridho"))
kb.add_fact(("Desi", "nenek dari", "Wanda"))
kb.add_fact(("Desi", "nenek dari", "Aji"))
kb.add_fact(("Desi", "nenek dari", "Gunawan"))
kb.add_fact(("Ana", "nenek dari", "Anggun"))
kb.add_fact(("Ana", "nenek dari", "Boy"))
# sepupu
kb.add_fact(("Tari", "sepupu dari", "Hamzah"))
kb.add_fact(("Tari", "sepupu dari", "Eka"))
kb.add_fact(("Tari", "sepupu dari", "Mira"))
kb.add_fact(("Tari", "sepupu dari", "Bastian"))
kb.add_fact(("Nurul", "sepupu dari", "Hamzah"))
kb.add_fact(("Nurul", "sepupu dari", "Eka"))
kb.add_fact(("Nurul", "sepupu dari", "Mira"))
kb.add_fact(("Nurul", "sepupu dari", "Bastian"))
kb.add_fact(("Yanto", "sepupu dari", "Hamzah"))
kb.add_fact(("Yanto", "sepupu dari", "Eka"))
kb.add_fact(("Yanto", "sepupu dari", "Mira"))
kb.add_fact(("Yanto", "sepupu dari", "Bastian"))
kb.add_fact(("Hamzah", "sepupu dari", "Tari"))
kb.add_fact(("Hamzah", "sepupu dari", "Nurul"))
kb.add_fact(("Hamzah", "sepupu dari", "Yanto"))
kb.add_fact(("Hamzah", "sepupu dari", "Eka"))
kb.add_fact(("Hamzah", "sepupu dari", "Mira"))
kb.add_fact(("Hamzah", "sepupu dari", "Bastian"))
kb.add_fact(("Eka", "sepupu dari", "Tari"))
kb.add_fact(("Eka", "sepupu dari", "Nurul"))
kb.add_fact(("Eka", "sepupu dari", "Yanto"))
kb.add_fact(("Mira", "sepupu dari", "Tari"))
kb.add_fact(("Mira", "sepupu dari", "Nurul"))
kb.add_fact(("Mira", "sepupu dari", "Yanto"))
kb.add_fact(("Bastian", "sepupu dari", "Tari"))
kb.add_fact(("Bastian", "sepupu dari", "Nurul"))
kb.add_fact(("Bastian", "sepupu dari", "Yanto"))
kb.add_fact(("Wanda", "sepupu dari", "Aji"))
kb.add_fact(("Wanda", "sepupu dari", "Gunawan"))
kb.add_fact(("Wanda", "sepupu dari", "Anggun"))
kb.add_fact(("Wanda", "sepupu dari", "Boy"))
kb.add_fact(("Aji", "sepupu dari", "Wanda"))
kb.add_fact(("Aji", "sepupu dari", "Anggun"))
kb.add_fact(("Aji", "sepupu dari", "Boy"))
kb.add_fact(("Gunawan", "sepupu dari", "Wanda"))
kb.add_fact(("Gunawan", "sepupu dari", "Anggun"))
kb.add_fact(("Gunawan", "sepupu dari", "Boy"))
kb.add_fact(("Anggun", "sepupu dari", "Wanda"))
kb.add_fact(("Anggun", "sepupu dari", "Aji"))
kb.add_fact(("Anggun", "sepupu dari", "Gunawan"))
kb.add_fact(("Boy", "sepupu dari", "Wanda"))
kb.add_fact(("Boy", "sepupu dari", "Aji"))
kb.add_fact(("Boy", "sepupu dari", "Gunawan"))

# Query the knowledge base
person = "Ridho"
relation = "paman dari"
related_people = kb.get_related_people(person, relation)

if related_people:
    print(f"{person} {relation} {', '.join(related_people)}")
else:
    print(f"No information found about {person} {relation}")
1